faf-client:
  server:
    host: test.faforever.com

  irc:
    host: irc.test.faforever.com

  ice:
    turn:
      host: test.faforever.com
    stun:
      host: test.faforever.com

  vault:
    base-url: http://content.test.faforever.com

  news:
    feed-url: http://direct.faforever.com/news/feed

  replay:
    remote-host: lobby.test.faforever.com

  api:
    base-url: http://japi.test.faforever.com
    access-token-uri: ${faf-client.api.base-url}/oauth/token
    client-id: faf-client
    client-secret: banana

  forged-alliance:
    exe-url: http://content.test.faforever.com/faf/updaterNew/updates_faf_files/ForgedAlliance.exe
